tickers = ['AAPL', 'MSFT', 'AMZN', 'FB', 'TSLA', 'GOOGL',
           'GOOG', 'JNJ', 'JPM', 'V', 'UNH', 'PG', 'NVDA',
           'DIS', 'MA', 'HD', 'BAC', 'VZ', 'ADBE', 'NFLX',
           'INTC', 'T', 'MRK', 'PFE', 'WMT', 'CRM', 'TMO',
           'ABT', 'PEP', 'KO', 'XOM', 'CSCO', 'ABBV', 'NKE',
           'AVGO', 'QCOM', 'CVX', 'ACN', 'COST', 'MDT', 'MCD',
           'NEE', 'TXN', 'DHR', 'HON', 'UNP', 'LIN', 'BMY',
           'WFC', 'C', 'AMGM', 'LLY', 'PM', 'SBUX', 'LOW',
           'ORCL', 'IBM', 'UPS', 'BA', 'MS', 'BLK', 'RTX',
           'CAT', 'GS', 'NOW', 'GE', 'MMM', 'INTU', 'CVS',
           'AMT', 'TGT', 'ISRG', 'DE', 'BKNG', 'SCHW', 'MU',
           'AMAT', 'LMT', 'FIS', 'TJX', 'ANTM', 'MDLZ', 'SYK',
           'CI', 'ZTS', 'AXP', 'SPGI', 'GILD', 'MO', 'LRCX',
           'BDX', 'ADP', 'CSX', 'CME', 'PLD', 'CB', 'CL', 'TFC',
           'ADSK', 'USB', 'PNC', 'DUK', 'FISV', 'CCI', 'ICE',
           'SO', 'NSC', 'APD', 'VRTX', 'ITW', 'SHW', 'D', 'FDX',
           'DD', 'HUM', 'EL', 'ADI', 'MMC', 'ECL', 'EW', 'PGR',
           'GM', 'DG', 'BSX', 'NEM', 'ETN', 'COF', 'REGN', 'EMR',
           'COP', 'AON', 'WM', 'MCO', 'NOC', 'FCX', 'ROP', 'KMB',
           'ROST', 'CTSH', 'KLAC', 'TEL', 'BAX', 'EXC', 'EA', 'APH',
           'AEP', 'APTV', 'STZ', 'MCHP', 'A', 'BIIB', 'SYY', 'CMG',
           'CDNS', 'LHX', 'MET', 'DVCM', 'JCI', 'TT', 'BK', 'XLNX',
           'PH', 'PPG', 'GIS', 'CMI', 'F', 'HPQ', 'GD', 'TRV', 'AIG',
           'TROW', 'EBAY', 'MAR', 'SLB', 'SRE', 'MNST', 'XEL', 'EOG',
           'ALXN', 'ORLY', 'CARR', 'ALL', 'PSA', 'ZBH', 'WBA', 'PRU',
           'YUM', 'PSX', 'CTAS', 'PCAR', 'ES', 'ROK', 'DFS', 'BLL',
           'MCK', 'PAYX', 'AFL', 'ADM', 'MSI', 'AZO', 'MPC', 'AME',
           'FAST', 'SWK', 'KMI', 'PEG', 'GLW', 'VFC', 'LUV', 'SPG',
           'WEC', 'OTIS', 'STT', 'DLTR', 'ENPH', 'WELL', 'WMB', 'DAL',
           'WY', 'LYB', 'BBY', 'CLX', 'KR', 'CERN', 'VLO', 'ED', 'AMP',
           'MKC', 'EIX', 'DTE', 'DHI', 'VIAC', 'WST', 'FITB', 'VRTS',
           'HSY', 'EFX', 'AVB', 'ZBRA', 'PXD', 'TER', 'VMC', 'PPL',
           'LH', 'PAYC', 'ETSY', 'LEN', 'O', 'CBRE', 'IP', 'QRVO', 'RSG',
           'NTRS', 'KSU', 'VRSN', 'EQR', 'XYL', 'ODFL', 'EXPE', 'MLM',
           'URI', 'LVS', 'TSN', 'ETR', 'MTB', 'CDW', 'DOV', 'AEE', 'GRMN',
           'OKE', 'HIG', 'KEY', 'GWW', 'HAL', 'PKI', 'CTLT', 'VTR', 'TYL',
           'IR', 'OXY', 'TSCO', 'STE', 'NUE', 'RF', 'AKAM', 'HES', 'DGX',
           'WDC', 'CMS', 'CAH', 'CAG', 'KMX', 'AES', 'ABC', 'WAT', 'DRI',
           'FE', 'VAR', 'EXPD', 'CTXS', 'FMC', 'NDAQ', 'POOL', 'K', 'CCL', 'PEAK',
           'BKR', 'DPZ', 'ESS', 'GPC', 'J', 'HBAN', 'EMN', 'NTAP', 'MAS',
           'NVR', 'OMC', 'RCL', 'AVY', 'BIO', 'STX', 'SJM', 'PFG', 'TDY',
           'CINF', 'CHRW', 'HRL', 'BXP', 'IFF', 'XRAY', 'NLOK', 'HAS',
           'WRK', 'WHR', 'PHM', 'CNP', 'TXT', 'ALLE', 'UHS', 'DVN', 'L', 'HWM',
           'LB', 'WYNN', 'PWR', 'LYV', 'LUMN', 'HST', 'BWA', 'TPR', 'RE', 'CPB',
           'LNC', 'IPG', 'SNA', 'WU', 'GL', 'WRB', 'MOS', 'TAP', 'PNR',
           'CF', 'NRG', 'DVA', 'PNW', 'CMA', 'MHK', 'NWL', 'NI', 'AIZ',
           'IRM', 'ZION', 'JNPR', 'PVH', 'NLSN', 'RHI', 'SEE', 'NWSA',
           'COG', 'BEN', 'IVZ', 'FLIR', 'KIM', 'APA', 'PRGO', 'MRO']
